kartoza/geonode

- geonode/local_settings.py.geoserver.sample
- geonode/local_settings.py.qgis.sample
- geonode/qgis_server/signals.py
- geonode/settings.py
I tried to clean a little bit the settings.
Some settings about geoserver where useless in our project.
@lucernae I think you should make a `local_settings.py.inasafe.sample` with your celery and inasafe headless inside and remove everything from settings.py and local_settings.
> refactor settings between geoserver and qgis

- geonode/base/models.py
- geonode/decorators.py
- geonode/layers/populate_layers_data.py
- geonode/local_settings.py.qgis.sample
- geonode/qgis_server/__init__.py
- geonode/tests/integration.py
- geonode/utils.py
Issue: #221 
For example, when Geoserver related function is decorated, it won't be executed if QGIS Server is used.
> Add decorator to check ogc backend used.

- geonode/qgis_server/urls.py
- geonode/qgis_server/views.py
use django as proxy for every OGC requests
@ismailsunni Is-it ok to remove all these specifics views in the app and just one view to forward the request to QGIS
I would like of course to add some unittest, but I need first some qgis layers in the test DB. @lucernae did you work on that before ?
> use django as proxy for every OGC requests

- .travis.yml
- docker-compose-qgis-server.yml
- geonode/base/models.py
- geonode/geoserver/helpers.py
- geonode/layers/models.py
- geonode/layers/utils.py
- geonode/local_settings.py.qgis.sample
- geonode/maps/models.py
- geonode/maps/qgis_server_views.py
- geonode/maps/templates/maps/map_leaflet.html
- geonode/maps/tests.py
- geonode/maps/views.py
- geonode/qgis_server/admin.py
- geonode/qgis_server/helpers.py
- geonode/qgis_server/models.py
- geonode/qgis_server/tasks/update.py
- geonode/qgis_server/tests/test_qgis_settings.py
- geonode/qgis_server/tests/test_views.py
- geonode/qgis_server/urls.py
- geonode/qgis_server/views.py
- pavement.py
- scripts/misc/qgis_server_setup.sh
- Refactor thumbnail url generator for QGIS Server. Now giving direct url to
QGIS Server, instead of proxying to Django.
- Remove unnecessary thumbnail view in qgis_server, because geonode already
have internal cache for thumbnail. Thumbnail should just be accessed
directly to QGIS Server without proxy.
- Fix map creation test.
- Refactor wrong/inconsistent bbox convention for maps.
> Fix maps test for qgis_server

- geonode/layers/forms.py
- geonode/layers/models.py
- geonode/layers/tests.py
- geonode/qgis_server/models.py
- geonode/qgis_server/signals.py
- geonode/qgis_server/urls.py
- geonode/qgis_server/views.py
- geonode/settings.py
- geonode/static/geonode/js/upload/FileTypes.js
- geonode/upload/files.py
- geonode/upload/views.py
Partial fix for #159 
Current state:
- We can't upload asc file
- We can upload tif file
This PR will make geonode able to upload asc file. We need to enable it first before we can download the asc file.
> Add ASCII file to geonode.

- geonode/qgis_server/signals.py
- geonode/qgis_server/urls.py
- geonode/settings.py
- geonode/tests/integration.py
This is a follow up from PR #232
> Add download zipped files for non-shapefile.

- geonode/qgis_server/helpers.py
- geonode/qgis_server/signals.py
- geonode/qgis_server/urls.py
- geonode/qgis_server/views.py
- geonode/urls.py
Maybe, before this PR, we need to fix the double qgis-server app in geonode urls.
If we go to : http://localhost/fake_url
We can see qgis-server urls are registered twice:
line 53 and 79-84
This PR also fixes the 404 page for the raw tile URL
BTW, @lucernae Shouldn't we do the same for geosafe? It's a good practice I think in django to have "subdomains" for each app.
> refactor URLs in qgis-server app

- geonode/layers/views.py
- geonode/tests/integration.py
This fix #108 
It seems there is not unit test to replace layer for geoserver. I will try to add one for qgis server backend.
Update: there is a unit test for it, I will try to unskip it for qgis server backend
> Make replace layer works with QGIS Server Backend.

- geonode/geoserver/tests.py
- geonode/layers/tests.py
- geonode/layers/utils.py
- geonode/qgis_server/models.py
- geonode/qgis_server/signals.py
- geonode/security/tests.py
- geonode/tests/integration.py
> Fix skipped tests.

- .travis.yml
Travis does apparently update their ubuntu trusty image and somehow our build is failing because it doesn't found osgeo.
We used previous image now until Travis is fine and stable.
> Fix osgeo package not found in travis.

- geonode/api/resourcebase_api.py
- geonode/context_processors.py
- geonode/layers/management/commands/delete_orphaned_layers.py
- geonode/layers/models.py
- geonode/layers/templates/layers/layer_detail.html
- geonode/layers/templates/layers/layer_leaflet_map.html
- geonode/layers/utils.py
- geonode/layers/views.py
- geonode/qgis_server/context_processors.py
- geonode/qgis_server/forms.py
- geonode/qgis_server/helpers.py
- geonode/qgis_server/management/__init__.py
- geonode/qgis_server/management/commands/__init__.py
- geonode/qgis_server/management/commands/delete_orphaned_qgis_server_layers.py
- geonode/qgis_server/management/commands/tests.py
- geonode/qgis_server/models.py
- geonode/qgis_server/signals.py
- geonode/qgis_server/tasks/update.py
- geonode/qgis_server/templates/qgis_server/forms/qml_style.html
- geonode/qgis_server/tests/test_views.py
- geonode/qgis_server/urls.py
- geonode/qgis_server/views.py
- Refactor additional fields in Layers api. Will fix #281 
- Edit Layer Styles interaction. For #206 
- Edit Layer > Set thumbnails functionality. For #206 
- Handled #282 . Overwrite related thumbnails and QGIS Server files, however still doesn't deal with orphaned files automatically.
> Additional features for Geonode - QGIS Server

- geonode/layers/templates/layers/layer_leaflet_map.html
- geonode/layers/tests.py
- geonode/layers/views.py
- geonode/qgis_server/helpers.py
- geonode/qgis_server/signals.py
- geonode/qgis_server/tasks/update.py
- geonode/qgis_server/views.py
- Skip bbox check for thumbnail creation. fix #287 
- Convert bbox to EPSG:4326 for displaying layers. fix #289 
- Try to retrieve layer projection and save Layer CRS. fix #287 
- Standardize thumbnail generation to use EPSG:4326. fix #287
> Code improvements

- geonode/layers/views.py
- geonode/qgis_server/middleware.py
- geonode/qgis_server/templates/qgis_server/forms/qml_style.html
Address remaining issue of #284 
Use middleware to apply more context.
Useful to avoid having edited geonode layers views in the future for qgis-server backend app.
> Hide QML Style download when not exists.

- geonode/api/api.py
- geonode/api/resourcebase_api.py
- geonode/api/urls.py
- geonode/layers/templates/layers/layer_detail.html
- geonode/layers/templates/layers/layer_leaflet_map.html
- geonode/layers/views.py
- geonode/local_settings.py.qgis.sample
- geonode/qgis_server/admin.py
- geonode/qgis_server/forms.py
- geonode/qgis_server/helpers.py
- geonode/qgis_server/migrations/0003_auto_20170727_0509.py
- geonode/qgis_server/migrations/0004_auto_20170805_0223.py
- geonode/qgis_server/models.py
- geonode/qgis_server/signals.py
- geonode/qgis_server/templates/qgis_server/forms/qml_style.html
- geonode/qgis_server/tests/test_helpers.py
- geonode/qgis_server/tests/test_views.py
- geonode/qgis_server/urls.py
- geonode/qgis_server/views.py
- geonode/tests/integration.py
Related with #149 
Work in progress:
TODO:
> Add style management for QGIS Server backend.

- geonode/maps/templates/leaflet_maps/map_view.html
fix zooming when two non-intersection layers are selected on create new map page
fix #298
Below is the snapshot.
@NyakudyaA the zoom level would determine how wide the layers can be shown on the map.
There are two illustration at the GIF.
the first illustration shows that two adjacent layers (Malawi and Tanzania) are drawn on the map. 
But, in the second illustration, it would be difficult when the two layers (Malawi and Nepal) have a large distance.
> fix wrong zoom

- geonode/layers/templates/layers/layer_leaflet_map.html
This fix will show form validation for style upload form.
It happens because the error callback does not properly replace the form's html code
Fix #335
> Fix form errors not shown in style upload

- geonode/maps/qgis_server_views.py
- geonode/maps/urls.py
partially fix #207
the working sample of removing map:
> fix set thumbnail and remove map

- geonode/maps/templates/maps/map_detail.html
> fix embed map bug on firefox

- geonode/layers/utils.py
> fix a bug on determining srid when upload a vector layer

- geonode/qgis_server/tasks/update.py
- geonode/qgis_server/tests/test_views.py
- geonode/qgis_server/views.py
> recreate thumbnail on setting new default style

- geonode/qgis_server/views.py
list of file extensions getting downloaded:
- raster layers: qgs, qml, tif, xml
- vector layers: dbf, prj, qgs, qml, shp, shx, xml
this is specific for qgis-server backend
fix #299
> include all files on maps' download data layer

- tasks.py
Based on input from GeoNode dev. It was intended that database user and name always be the same.
> Revert "Change environment variable name for database user"

- geonode/layers/utils.py
- geonode/maps/templates/maps/map_leaflet.html
- geonode/qgis_server/helpers.py
- geonode/qgis_server/signals.py
- geonode/qgis_server/tasks/update.py
- geonode/qgis_server/tests/test_views.py
- geonode/tests/integration.py
- Let GeoServer and QGIS Server handle misprojection issues if GeoNode can't handle it
- QGIS Server will always transform bbox to EPSG 4326 to work consistently with leaflet
- QGIS Server thumbnail request will try to maintain aspect ratios of the
requested extent to avoid squashed image
- Most of the problem is because main geonode docker image uses GDAL 1. It can't detect most EPSG. This is fixed in: https://github.com/kartoza/geonode-docker/commit/db60cae03b78a1addfeb468f5a9b3e6117d029b7
- Even if using GDAL 2, sometimes it can't detect correct EPSG code (which is needed to draw correct bbox in leaflet). GeoServer can detect it correctly. In our case (QGIS Server) we transform the bbox to EPSG:4326 by default. The actual CRS is preserved in the file and handled by QGIS. Example layer …
> Fix qgis server bound projection

- docker-compose-qgis-server.yml
- geonode/client/templates/leaflet/layers/layer_leaflet_map.html
- geonode/qgis_server/context_processors.py
- geonode/qgis_server/helpers.py
- geonode/qgis_server/signals.py
- geonode/qgis_server/tasks/update.py
- geonode/qgis_server/tests/test_views.py
- geonode/qgis_server/views.py
- geonode/settings.py
- We can optionally add default basemap to QGIS Project for Layer
- We can use that basemap to create thumbnail
- Choose different basemap via Layer Detail --> Set Thumbnail
- Needs https://github.com/kartoza/otf-project/pull/12
- Overrides/follow up https://github.com/kartoza/geonode/pull/446
> Add basemap to QGIS Project

- geonode/templates/metadata_detail.html
change `Projection System` into `Coordinate Reference System` in Metadata Detail page
fix #418
> change wording in Metadata Detail page

- dev_config.yml
- geonode/layers/utils.py
- geonode/qgis_server/models.py
- geonode/qgis_server/signals.py
- geonode/qgis_server/tests/test_views.py
- geonode/tests/integration.py
- Improve unittests for Layer Metadata Upload (overwrite flag=False, like in the form)
- Refactor missprojection handling for QGIS Server Raster layer
- Change build server URL. Fix #501
> Handle missprojection for raster layer reupload

- geonode/people/adapters.py
We need to strip base URL from '/' endings, because when it is used in the template, the variable are concatenated directly with relative url from Django reverse. This will avoid URL such as:
```
http://testing.geonode.kartoza.com//relative/url
```
> Change for proper SITEURL format in invitation email

- geonode/qgis_server/helpers.py
- geonode/qgis_server/signals.py
the end result will be similar to the abandon #472
fix #406
fix #325
> Add styles to qgs file

- geonode/settings.py
the value should be equal to `link_name` in geonode/qgis_server/signals.py
fix #504
> restore zipped shapefile download for vector layers in layer detail page

- geonode/qgis_server/helpers.py
- geonode/qgis_server/tests/test_views.py
fix for #497 #517 
Now, after we got meters unit, we can properly calculate new extent based on GeoNode default aspect ratios: [200, 150] pixels. We used 400, 300 for clarity, because we displayed the basemap. It helps for the label resolutions to become readable.
There are some weird bug though.
Previously, when we request to WMS in QGIS Server, we provided bbox in the format: [ymin,xmin,ymax,xmax] in EPSG:4326.
However, in EPSG:3857, I had to use [xmin,ymin,xmax,ymax] for it to display the correct extent (took me a while to realize). I don't know if this is expected from QGIS Server, cc @gubuntu ?
> Fix thumbnail to default aspect ratios

- geonode/qgis_server/tests/test_views.py
- geonode/qgis_server/views.py
> add qml and xml files when downloading a layer in zip and geotiff formats
