kartoza/geonode

- geonode/layers/urls.py
- geonode/layers/views.py
- geonode/maps/templates/new_maps/map_view.html
- geonode/qgis_server/views.py
> Map view cosmetics

- geonode/layers/views.py
- geonode/maps/new_views.py
- geonode/maps/templates/new_maps/map_view.html
- geonode/static/geonode/css/base.css
- Update from Maria
- Create map from layer or cart
- Remove layer from dropdown after being added
> Qgis server

- geonode/layers/models.py
- geonode/static/geosafe/js/analysis.js
- geosafe/static/geosafe/js/analysis.js
- geosafe/templates/geosafe/analysis/create.html
- geosafe/templates/geosafe/analysis/list.html
- geosafe/templates/geosafe/analysis/modal/impact_card.html
- geosafe/views/analysis.py
> Geosafe UI fixes

- .gitignore
- geonode/qgis_server/__init__.py
- geonode/qgis_server/admin.py
- geonode/qgis_server/gis_tools.py
- geonode/qgis_server/models.py
- geonode/qgis_server/signals.py
- geonode/qgis_server/tasks/__init__.py
- geonode/qgis_server/tasks/update.py
- geonode/qgis_server/urls.py
- geonode/qgis_server/views.py
> code quality cleanup

- .travis.yml
- docker-compose-qgis-server.yml
- geonode/geoserver/tests.py
- geonode/layers/tests.py
- geonode/local_settings.py.qgis.sample
- geonode/maps/tests.py
- geonode/qgis_server/signals.py
- geonode/security/models.py
- geonode/security/tests.py
- geonode/tests/integration.py
- geonode/tests/smoke.py
- pavement.py
WIP.
Experiment by using qgis-server docker for integration tests.
> include QGIS Server integration in Travis

- .travis.yml
- geonode/tests/integration.py
Include branch for local testing in this repo
> Include branch master-qgis_server to travis.yml

- geonode/layers/utils.py
Needed for geosafe.
Geosafe put some report information in a json file.
> Add json file acceptance for qgis-server backend

- geonode/messaging/management/__init__.py
- geonode/qgis_server/signals.py
- geonode/qgis_server/tasks/update.py
- geonode/tests/integration.py
Related with #172 :
- Fix thumbnail tests for layer and map
- Add thumbnail for map
> Fix Thumbnail Tests

- geonode/api/resourcebase_api.py
Regarding issue #179:
* include layer links in layers API
* include map layer list in maps API
* include geonode version in output for resource based API
> improve geonode API:

- geonode/base/models.py
- geonode/layers/views.py
- geonode/local_settings.py.qgis.sample
- geonode/maps/templates/leaflet_maps/map_view.html
- geonode/maps/templates/maps/map_leaflet.html
- geonode/qgis_server/signals.py
- geonode/qgis_server/urls.py
- geonode/tests/csw.py
* Fix map thumbnail #191 
* Fix map creation
* Fix map layer overlay using WMS connection
> Fix map functionality when using QGIS Server backend

- .travis.yml
This is to refrain from bothering them with unnecessary emails
> Comment out core geonode developer notification

- geonode/local_settings.py.qgis.sample
- geonode/qgis_server/signals.py
- geonode/qgis_server/tasks/update.py
- geonode/qgis_server/tests/__init__.py
- geonode/qgis_server/tests/qgis_settings_test.py
- geonode/tests/integration.py
- pavement.py
Add some test file to check that geonode settings is properly configured for qgis_server backends.
> Add tests for qgis integration

- .travis.yml
- geonode/local_settings.py.qgis.sample
Codecov supports multiple build matrix coverage report.
> Add codecov for coverage tests

- geonode/qgis_server/views.py
* use get_object_or_404 instead having many lines each time
* use requests from python instead building or our own query string
I have more to come
> refactor qgis views

- geonode/layers/templates/layers/layer_leaflet_map.html
- geonode/qgis_server/views.py
I don't know how we test the UI at the moment. So I'll just merge it after test passed.
Also fix some typo that I accidentally found.
> Fix leaflet map to not show tile and wms at the same time

- geonode/qgis_server/signals.py
- geonode/qgis_server/urls.py
- geonode/qgis_server/views.py
- geonode/settings.py
Remove download ASC file link.
> Remove asc link.

- geonode/qgis_server/helpers.py
- geonode/qgis_server/models.py
- geonode/qgis_server/tests/test_views.py
- geonode/qgis_server/urls.py
- geonode/qgis_server/views.py
this PR adds one OGC server per layer too
> refactor helpers about WMS calls

- geonode/base/management/commands/backup.py
- geonode/base/management/commands/helpers.py
- geonode/base/management/commands/migrate_layers.py
- geonode/base/management/commands/restore.py
- geonode/base/management/commands/settings.ini
- geonode/layers/templates/layers/layer_leaflet_map.html
- requirements.txt
- setup.py
Regular update from geonode/master
> Master merged 2

- geonode/api/resourcebase_api.py
@lucernae can you review it? And deploy it to both staging? I need it for GeoNode QGIS Client
> Add name and typename in layer API.

- geonode/qgis_server/signals.py
- geonode/qgis_server/views.py
- geonode/tests/csw.py
> add WMS, WFS remote thumbnail links

- geonode/qgis_server/helpers.py
- geonode/qgis_server/migrations/0002_qgisservermap.py
- geonode/qgis_server/models.py
- geonode/qgis_server/signals.py
- geonode/qgis_server/tasks/update.py
- geonode/qgis_server/views.py
> Refactor QGIS Server Url generation.

- geonode/qgis_server/helpers.py
- geonode/qgis_server/tests/test_helpers.py
- geonode/qgis_server/tests/test_views.py
- geonode/qgis_server/views.py
- geonode/tests/smoke.py
Trying to fix unittest from changes in new QGIS Server LTR
> Improve unittests

- geonode/maps/templates/leaflet_maps/map_view.html
- requirements.txt
now using django-leaflet 0.22.0 a.k.a. leaflet 1.0.3
fix #295
> use latest leaflet

- geonode/qgis_server/helpers.py
Make sure that tile url not quoted.
> Fix quoted tile url

- geonode/maps/templates/leaflet_maps/map_view.html
- geonode/static/lib/css/easy-button.css
- geonode/static/lib/js/easy-button.js
fix #296 
*Note:* 
i propose using easy-button in geonode. this commit will add `easy-button.css` and `easy-button.js` to the geonode. when approved, geosafe will need some code refactoring, particularly to refer the easy-button library from geonode rather than it's own folder.
below is the demo:
> add global zoom

- geonode/api/api.py
- geonode/api/resourcebase_api.py
- geonode/api/tests.py
- geonode/api/urls.py
- geonode/base/populate_test_data.py
- geonode/layers/forms.py
- geonode/layers/models.py
- geonode/layers/views.py
- geonode/maps/urls.py
- geonode/qgis_server/management/commands/import_qgis_styles.py
- geonode/qgis_server/management/commands/tests.py
- geonode/qgis_server/migrations/0005_auto_20170823_0341.py
- geonode/qgis_server/models.py
- geonode/qgis_server/tests/data/test_grid.qml
- geonode/qgis_server/tests/test_views.py
- geonode/qgis_server/urls.py
- geonode/qgis_server/views.py
- geonode/static/geonode/js/upload/LayerInfo.js
- geonode/upload/forms.py
- Add import qgis style management command
Related with #309 
- Wrap for Geoserver and QGIS Server backend
- Add POST and DELETE method for Styles API
- Add unittests
> QGIS Style support improve

- geonode/api/api.py
- geonode/api/resourcebase_api.py
- geonode/api/tests.py
- pavement.py
WIP. Used for testing Travis environment.
Related with #309 
- Fix unittest for Geoserver Styles API
- Add Delete method for Styles
- Add Patch method for Layers to set default style
> Improvement for Styles API

- geonode/api/resourcebase_api.py
- geonode/api/tests.py
- Code improvement to control Links field
> Small patch for Layers API

- geonode/layers/templates/layers/layer_detail.html
- geonode/qgis_server/signals.py
- geonode/qgis_server/urls.py
- geonode/qgis_server/views.py
- geonode/settings.py
note: these code depend on kartoza/otf-project#11
fix #157
The GIF:
> add download QGS layer file

- geonode/layers/templates/layers/layer_detail.html
- geonode/qgis_server/signals.py
- geonode/qgis_server/urls.py
- geonode/qgis_server/views.py
- geonode/settings.py
The QLR would be able to open using QGIS desktop
this code should work along with kartoza/otf-project#10
fix #154
below is the illustration:
> download a QLR file for a layer

- geonode/qgis_server/helpers.py
- geonode/qgis_server/views.py
using layername instead of title
code refactoring: url is generated on the helpers.py
> bug fix on qgs and qlr layer

- geonode/qgis_server/xml_utilities.py
- Allow to fail gracefully if the metadata structure is not expected
> Fix for xml metadata utilities

- geonode/qgis_server/helpers.py
- geonode/qgis_server/signals.py
- geonode/qgis_server/views.py
- geonode/settings.py
- change wording for QLR and QGS
- change the filename
- also code refactoring
fix kartoza/geosafe#233
> UI changes

- geonode/maps/qgis_server_views.py
- geonode/maps/templates/maps/map_detail.html
- geonode/maps/urls.py
- geonode/maps/views.py
- geonode/qgis_server/signals.py
this PR is different from #321 because it implements Links
fix #155
> download QLR file on map using links

- geonode/layers/templates/layers/layer_detail.html
- geonode/layers/views.py
this commit is required for kartoza/geosafe#240 to work properly
fix kartoza/geosafe#224
> improve geosafe report button

- geonode/maps/qgis_server_views.py
> fix copying a map

- pavement.py
> update pavement.py from upstream

- geonode/layers/templates/layers/layer_detail.html
> fix data tab

- geonode/maps/qgis_server_views.py
- geonode/maps/views.py
- geonode/qgis_server/tests/test_views.py
- geonode/qgis_server/views.py
test scenario for: #154 #155 #157
> add QLR and QGS unittest for layer and map

- geonode/maps/qgis_server_views.py
- geonode/maps/templates/leaflet_maps/map_embed.html
- geonode/maps/templates/maps/map_detail.html
- geonode/maps/tests.py
- geonode/maps/urls.py
- geonode/maps/views.py
> Download leaflet page #151

- geonode/maps/qgis_server_views.py
- geonode/maps/templates/leaflet_maps/map_edit.html
- geonode/maps/templates/leaflet_maps/map_embed.html
@boney-bun can you review this one? I tried to fix some code you implement (some got wrecked by upstream). Can you check the functionality and my review on it?
Summary:
- Fixed Iframe view for Map Embed Iframe (tested using jsfiddle.net)
- Fixed edit map behaviour with several problems:
- Code quality: reduce duplicate javascript instruction that will possibly slow down the map edit view if the layer list gets very large. Refactor it to use function and JSON serialization (should have been using an API in the next iteration).
- Change layer.typename into layer.alternate (undetected code refactor because this is in django templates). This changes follows upstream model field.
- Add missing map.fitBounds instruction for map embed download. This will fit the extent
- Change layer.visibility …
> Refactor and fix maps functionality

- geonode/qgis_server/signals.py
- geonode/qgis_server/tests/test_views.py
new text : QGIS layer file (.qlr)
old text: QLR Layer file
fix #390
> fix QLR text on map download

- geonode/client/templates/leaflet/maps/map_detail.html
- geonode/client/templates/leaflet/maps/map_edit.html
- geonode/client/templates/leaflet/maps/map_embed.html
- geonode/maps/qgis_server_views.py
- geonode/maps/urls.py
- geonode/qgis_server/signals.py
- geonode/qgis_server/tests/test_views.py
- geonode/qgis_server/views.py
> fix map functionalities

- geonode/maps/qgis_server_views.py
> fix filename extension in download map leaflet

- Dockerfile
Allows variable FROM statement
> Modify Dockerfile build script

- requirements.txt
Add missing uWSGI package for production
> Add uWSGI in requirements.txt

- tasks.py
Specify database user from environment.
> Change environment variable name for database user

- geonode/qgis_server/views.py
revision of #449: all files, but qgs
fix #299
> fix download all files on download data layer

- geonode/layers/forms.py
- geonode/layers/models.py
- geonode/layers/tests.py
- geonode/layers/utils.py
- geonode/qgis_server/models.py
- geonode/static/geonode/js/upload/FileTypes.js
> Add geojson suppport

- geonode/qgis_server/signals.py
Fix my stupid bug where I update all layers instead of just this one particular layer.
> Fix bug bounding box update all layers

- .travis.yml
- geonode/layers/models.py
- pavement.py
This warning came from false negative because a GeoJSON file is treated as Shapefile.
> Fix minor warning on Shapefile upload

- geonode/maps/qgis_server_views.py
- geonode/qgis_server/views.py
> removes space and a few other characters from the file name in download section

- geonode/layers/utils.py
- geonode/qgis_server/tests/test_views.py
- geonode/qgis_server/views.py
- geonode/tests/integration.py
Fix various issues about metadata saving
> Fix upload metadata

- .travis.yml
- dev_config.yml
- pavement.py
- scripts/misc/geoserver_setup_patch.sh
Related with #501 
This commit attempts to copy over GeoServer lib from docker images to
host directory, because regular GeoServer war files not able to run.
> Temporary fix commit for GeoServer travis unittests

- geonode/client/templates/leaflet/maps/map_detail.html
> hide Create A New Map button from public

- geonode/layers/forms.py
- geonode/layers/models.py
- geonode/layers/utils.py
- geonode/qgis_server/models.py
- geonode/qgis_server/qlr.py
- geonode/qgis_server/signals.py
- geonode/qgis_server/tests/data/buildings.qlr
- geonode/qgis_server/tests/test_views.py
- geonode/static/geonode/js/upload/FileTypes.js
Related with kartoza/geonode#422
> Add QLR Upload support for remote datasource

- geonode/qgis_server/gis_tools.py
- geonode/qgis_server/helpers.py
- geonode/qgis_server/management/commands/tile_seeder.py
- geonode/qgis_server/tasks/update.py
- geonode/qgis_server/tests/test_helpers.py
- geonode/qgis_server/views.py
- requirements.txt
To be used for #422 in rancher scheduled services
> Add tile seeder management command

- geonode/qgis_server/models.py
- geonode/qgis_server/tests/test_helpers.py
- Useful when passing style to other resources
> Add support for extracting default style as QML file

- geonode/qgis_server/views.py
> add qml files when downloading data layers

- geonode/templates/base.html
Fix https://github.com/kartoza/IGRAC-GGIS/issues/24
> Hide About in the footer for unregistered users

- geonode/documents/templates/documents/document_metadata_advanced.html
- geonode/documents/templates/documents/document_thumb_upload.html
- geonode/documents/templates/documents/document_upload_base.html
- geonode/geoserver/createlayer/templates/createlayer/layer_create.html
- geonode/layers/templates/layers/layer_granule_remove.html
- geonode/layers/templates/layers/layer_metadata_advanced.html
- geonode/layers/templates/layers/layer_metadata_upload.html
- geonode/layers/templates/layers/layer_remove.html
- geonode/layers/templates/layers/layer_replace.html
- geonode/layers/templates/layers/layer_style_upload.html
- geonode/layers/templates/upload/layer_upload.html
- geonode/layers/templates/upload/layer_upload_base.html
- geonode/layers/templates/upload/layer_upload_metadata_base.html
- geonode/maps/templates/maps/map_metadata_advanced.html
- geonode/services/templates/services/services_base.html
- geonode/settings.py
- geonode/templates/500.html
- geonode/templates/base.html
- igrac/__init__.py
- igrac/apps.py
- igrac/models.py
- igrac/signals.py
Fix https://github.com/kartoza/IGRAC-GGIS/issues/25
> Filter Layer, Maps, and Documents by user's groups by default

- igrac/static/css/base-igrac.css
- igrac/templates/landing_page.html
Fix https://github.com/kartoza/IGRAC-GGIS/issues/36
> Add description to map gallery

- geonode/static/geonode/css/base.css
- geonode/static/geonode/css/default.css
- igrac/static/css/base-igrac.css
Fix https://github.com/kartoza/IGRAC-GGIS/issues/38
> Fix footer problem

- igrac/urls.py
fix https://github.com/kartoza/IGRAC-GGIS/issues/37
> shorten url

- geonode/documents/templates/documents/document_metadata_advanced.html
- geonode/documents/templates/documents/document_thumb_upload.html
- geonode/documents/templates/documents/document_upload_base.html
- geonode/geoserver/createlayer/templates/createlayer/layer_create.html
- geonode/layers/templates/layers/layer_granule_remove.html
- geonode/layers/templates/layers/layer_metadata_advanced.html
- geonode/layers/templates/layers/layer_metadata_upload.html
- geonode/layers/templates/layers/layer_remove.html
- geonode/layers/templates/layers/layer_replace.html
- geonode/layers/templates/layers/layer_style_upload.html
- geonode/layers/templates/upload/layer_upload.html
- geonode/layers/templates/upload/layer_upload_base.html
- geonode/layers/templates/upload/layer_upload_metadata_base.html
- geonode/maps/templates/maps/map_metadata_advanced.html
- geonode/services/templates/services/services_base.html
- geonode/settings.py
- geonode/templates/500.html
- geonode/templates/base.html
- igrac/context_processors.py
- igrac/signals.py
- igrac/utilities.py
Fix https://github.com/kartoza/IGRAC-GGIS/issues/43
Previously, user must logout first to update the default filter by their group. This is because the filter is set when they login using signals. Now, the filter is set using context processor, so the filter will be updated with every request, no need to logout.
> Fix default filter by group

- geonode/static/geonode/css/default.css
- geonode/templates/base.html
- igrac/templates/landing_page.html
fix https://github.com/kartoza/IGRAC-GGIS/issues/11
> update landing page

- geonode/static/geonode/css/default.css
- geonode/templates/base.html
- igrac/static/css/base-igrac.css
- igrac/templates/landing_page.html
fix https://github.com/kartoza/IGRAC-GGIS/issues/45
> update landing page layout

- .github/workflows/main.yml
- requirements_igrac.txt
- scripts/spcgeonode/django/Dockerfile
This github action will try to build and push docker image when there is a new push to IGRAC branch.
> Update github workflow

- .gitmodules
> change gwml repo

- geonode/settings.py
add settings for gwml2 as different database
> add gwml2 as different database

- geonode/templates/base.html
fix https://github.com/kartoza/IGRAC-GGIS/issues/43
> fix filter

- requirements_igrac.txt
this fix https://github.com/kartoza/IGRAC-GGIS/issues/37
> remove view from map url

- geonode/base/admin.py
this fix https://github.com/kartoza/IGRAC-GGIS/issues/396
> Fix keywords field is required on the admin
